### ISSUE TITLE
Improved History Access

### ISSUE THREAD

**Issue by ktopolov** [hoangKnLai/vscode-ipython#1]
Assume I ran cell A, then cell B. When clicking up arrow, I see my history which contains the contents of Cell B:    
![image](https://user-images.githubusercontent.com/25532284/136472087-be7b1a0f-ab1b-41ce-a3c8-429a723c30f4.png)  
  
I'd expect that clicking the up arrow a second time would show me the contents of cell A; however, it simply moves my cursor up one line and continues showing the contents of cell B. This makes navigation through history slow.  
  
Suggestion would be to either:  
*  Replace up arrow when using iPython console such that it navigates one full executed block of lines at a time, or:  
*  Add new keyboard shortcut (control + up?)  

**EXIT**: Support to move up by a full executed group of lines in one click in the console.

**Comment by hoangKnLai** [comment]
Command history is solely managed by the IPython console.  It seems that the console already use (Ctrl + Up/Down) to navigate command history.  For some reason IPython docs don't have much on their keyboard shortcuts.  

Here is a page with some shortcuts and description:  [Command-History-Shortcuts](https://jakevdp.github.io/PythonDataScienceHandbook/01.02-shell-keyboard-shortcuts.html#Command-History-Shortcuts)
