### ISSUE TITLE
Send current line.

### ISSUE THREAD

**Issue by Ubaldo79** [hoangKnLai/vscode-ipython#11]
**Improvement suggestion:** A  very useful feature would be to send only the current line. Both `Matlab `and `Spyder `have it and it is widely used by the users of these apps. I am sure that `VSCode `users would enjoy it as well! :)

**Comment by FabianHofmann** [comment]
@hoangKnLai, I think this would be a very helpful feature. If you want, you could point me to the part where this would be implemented and I could try to draft a PR.

**Comment by hoangKnLai** [comment]
Happy to have someone else working on this project 😄.  

Hmm.  Where to start...  

At the moment, the framework is like this:    

- For any IPython Command, call `cmd, nExec = getIpythonCommand(document, selection)` --> `execute(terminal, cmd, nExec)`
   - `execute` simply `sendText` to console with some time delay between each send  

An option is to look into extending `runCursor()` which uses the framework above.  

P.S. I really should start actually commenting the code properly to typescript standard.

**Comment by WilliamsTravis** [comment]
Hi, thanks so much for this extension it's working great for me! I would also find the single line execution useful, so I'd like to second Ubaldo79's comment.  In the meantime, as a work around for anyone else who'd like this, a combination of the multi-command extension and this one has been working for me with this key binding in `keybindings.json`: 
```
    {
        "key": "f9",
        "command": "extension.multiCommand.execute",
        "args": {
            "sequence": [
                "expandLineSelection",
                "ipython.runSelections",
                "cursorRight"
            ]
        }
    }
```

**Comment by hoangKnLai** [comment]
Plan to deploy today's update soon which includes:
- Handling for a `run line at cursor` that also works for multi-cursor selections. 
   - Basically, any empty cursor anywhere is the same as selected a line at that cursor position
   - Three cursors: 1 select line 4, 1 on line 6 (without selection), and 1 partial selection on line 8
   ![image](https://user-images.githubusercontent.com/64025449/179405396-98aaf196-50e2-4000-9181-3a63f72fe13f.png)
   ![image](https://user-images.githubusercontent.com/64025449/179405439-8fc26fbd-0bde-4270-b03b-a11667937aa8.png)
   - NOTE: line 6 cursor is none so it defaulted to use the whole line (trimmed to handle indent error), and stacked into a single run.  This helps with the race conditions between `vscode.sendText() to IPy.In[n] to IPy.Out[n]`.
- Better handling of code block and cells:
  - Remove empty lines in a code block
  - Left trim line while preserving `python` indentation. E.g., 
    ```python
    # Editor:
    for _ in range(4):
        # %% Indented Cell with empty line(s) can now be executed correctly
        i = 1
        print('test 1')
        if i % 2:
            print('i % 2')

            print('i % 2 + 1')
    ```
    ```ipython
    # IPython:
    In [1]: # %% Indented Cell 1
       ...: print('test 1')
       ...: if i % 2:
       ...:     print('i % 2')
       ...:     print('i % 2 + 1')
       ...: 
    test 1    
    ```
    - NOTE: a weird side effect with sending text block is IPython not always rendering the `Out[n]: test 1` and just `test 1`. Definitely not very `pythonic` 😉. 
    ```python
    # Editor:
    # NOTE: consequently also handle this hanging case   
    if True:  # a code block
        # ... some other code    
        # %% Indented Cell in a code block
        print('test 2\r\n test 3')

    # Code outside the `if` code block but inside a cell
    print([1, 2, 3, 4, '5'])

    # NOTE: running the cell is equivalent to running all codes in the cell and the indent-handling  
    # now correctly adjust it to unexpected indent error. 
    ```
    ```ipython
    # IPython:
    In [2]: # %% Indented Cell 2
      ...: print('test 2\r\n test 3')
      ...: print([1, 2, 3, 4, '5'])
    test 2
     test 3
    [1, 2, 3, 4, '5']
    ```

**Comment by WilliamsTravis** [comment]
Works like a charm! Bravo.
