### ISSUE TITLE
Save file upon running

### ISSUE THREAD

**Issue by ma-sadeghi** [hoangKnLai/vscode-ipython#16]
It'd be great if the extension could save the file (if modified) prior to running it. It's currently a hassle especially for rapid prototyping.

**Comment by hoangKnLai** [comment]
This should be resolved in the next v2022.9.x hotfix.

**Comment by hoangKnLai** [comment]
@ma-sadeghi, can you close the issue if the problem is fixed for you? Thanks.

**Comment by ma-sadeghi** [comment]
Thank you so much, indeed it got fixed in the latest release.
