### ISSUE TITLE
Creating ipython terminal not sending startup commands

### ISSUE THREAD

**Issue by austinjtravis** [hoangKnLai/vscode-ipython#2]
When creating a new terminal the two startup commands `%load_ext autoreload`, `%autoreload 2` are not being sent to the ipython console.  This causes errors when exiting the terminal.  
![image](https://user-images.githubusercontent.com/57072875/137330355-9c5b5a4b-08c5-427b-a37a-958e6a72328a.png)  

**Suggestions**  
* Could just add a short pause before sending commands to terminal to allow time for ipython console to be created.

**Comment by austinjtravis** [comment]
Most recent release solved the startup issue, but if I `f9`  to run a line and create a new terminal the command is not sent to the ipython console.   

**Steps to reproduce**:  
1. Without a ipython console `f9` on a line of code   
   - I did `f9` around a string called `name` 
2. should see 
![image](https://user-images.githubusercontent.com/57072875/137499168-547810ba-6923-4335-a8b8-8adb43b676c1.png)
3. `exit()`  
   - sends the `f9` command to the terminal after exiting:  
   ![image](https://user-images.githubusercontent.com/57072875/137499356-6c65a635-510c-4a58-91c1-54ce5f26abb7.png)

**Comment by zhengzh** [comment]
```
ipython --no-autoindent --InteractiveShellApp.exec_lines= --InteractiveShellApp.exec_lines='%load_ext autoreload' --InteractiveShellApp.exec_lines='%autoreload 2'
```
```
[TerminalIPythonApp] CRITICAL | Bad config encountered during initialization:
[TerminalIPythonApp] CRITICAL | The 'exec_lines' trait of a TerminalIPythonApp instance must be a list, but a value of type 'unicode' (i.e. u'%autoreload 2') was specified.
```
When start-up a new IPython terminal, the commands give this error, please help!

**Comment by hoangKnLai** [comment]
> ```
> ipython --no-autoindent --InteractiveShellApp.exec_lines= --InteractiveShellApp.exec_lines='%load_ext autoreload' --InteractiveShellApp.exec_lines='%autoreload 2'
> ```
> 
> ```
> [TerminalIPythonApp] CRITICAL | Bad config encountered during initialization:
> [TerminalIPythonApp] CRITICAL | The 'exec_lines' trait of a TerminalIPythonApp instance must be a list, but a value of type 'unicode' (i.e. u'%autoreload 2') was specified.
> ```
> 
> When start-up a new IPython terminal, the commands give this error, please help!

Hi, can you provide the IPython you're using? As you might noticed in a previous post https://github.com/hoangKnLai/vscode-ipython/issues/2#issuecomment-944324377, the working IPython version is 7.28.0

**Comment by zhengzh** [comment]
Thanks for your response! IPython version is 7.28.0, I update the traitlets version to `traitlets-5.1.1`, and it worked

**Comment by hoangKnLai** [comment]
IPython console is created per sendText to the terminal asynchronously so sometime this causes a race condition with the command sendText to execute code.  Not much can be done without some official changes at the IPython API level.  Maybe some official hook for VSCode which I doubt will happen anytime soon.  

For now, for slow computer recommend starting the IPython console manually first.  Then run your code.
