### ISSUE TITLE
Empty --InteractiveShellApp.exec_lines= not needed

### ISSUE THREAD

**Issue by LordMero** [hoangKnLai/vscode-ipython#21]
```typescript
 if (cmds !== undefined) {
      startupCmd = " --InteractiveShellApp.exec_lines=";
```
This empty argument is not necessary and crashes the launch.

**Comment by hoangKnLai** [comment]
Got it.  Will fix soon.

**Comment by hoangKnLai** [comment]
Just published v2023.2.2 with fixes.   If your issue is fixed, please leave a comment and close this issue.  Thanks!

**Comment by LordMero** [comment]
Thanks. That's better but I am still having this issue: 

```shell
[TerminalIPythonApp] CRITICAL | Bad config encountered during initialization:
[TerminalIPythonApp] CRITICAL | The 'exec_lines' trait of a TerminalIPythonApp instance must be a list, but a value of class 'str' (i.e. '%autoreload 2') was specified.
```

**Comment by hoangKnLai** [comment]
I'll need help with replicating the problem.  Can you give me screenshot of the terminal `ipython ...` call and what version of IPython you're using?

**Comment by LordMero** [comment]
<img width="679" alt="image" src="https://user-images.githubusercontent.com/17352459/222088015-fff6b259-25e2-4aea-b363-b204c16e0c09.png">

The ipython version is: 7.19.0

**Comment by hoangKnLai** [comment]
Hmm, looks like either a bad setting or something wrong with IPython terminal configuration.  Are you using a custom IPython profile or something like that?  

For reference, here are some configuration I'm using to test the extension: 
- My `ipython` extension setting
![image](https://user-images.githubusercontent.com/64025449/222906341-511048ff-9932-438c-9e8b-93f0f6f71030.png)
- My `setting.json` with the extra `StartupCommands`: 
```json
    "ipython.CommandLineArguments": "--verbose -h \"test\" --hello -Earth \"World\"",
    "ipython.RunArguments": "-t -N32",
    "ipython.ExecutionLagMilliSec": 96,
    "terminal.integrated.enableMultiLinePasteWarning": false,
    "ipython.LaunchArguments": "--no-autoindent      --matplotlib",
    "ipython.SendCommandMethod": "file",
    "ipython.StartupCommands": [
      "%load_ext autoreload",
      "%autoreload 2"
    ]
```
- What my IPython terminal startup looks like:
```python
user@DESKTOP:~/Python$ source /home/user/.virtualenv/homework/bin/activate
(homework) user@DESKTOP:~/Python$ ipython --no-autoindent --matplotlib --InteractiveShellApp.exec_lines='%load_ext autoreload' --InteractiveShellApp.exec_lines='%autoreload 2' 
Python 3.8.10 (default, Jun 22 2022, 20:18:18) 
Type 'copyright', 'credits' or 'license' for more information
IPython 8.5.0 -- An enhanced Interactive Python. Type '?' for help.
Using matplotlib backend: agg

In [1]: print('Hello, World!')
Hello, World!

In [2]: 
```

**Comment by LordMero** [comment]
ok thanks. I'll close the issue!
