### ISSUE TITLE
Dedicated window for plots?

### ISSUE THREAD

**Issue by ma-sadeghi** [hoangKnLai/vscode-ipython#4]
Hi,

Let me first thank you for this creating this great piece of code! I'm not sure if you're familiar with Spyder IDE, but the only reason that stopped me from switching to vscode was its nice embedded IPython console, and here we are, I found your extension, and I find myself using vscode more and more. Thanks a lot!

Now back to my original question: is it possible to add a dedicated panel for plots (similar to Spyder IDE)?

Thanks once again,
Amin

**Comment by hoangKnLai** [comment]
> Let me first thank you for this creating this great piece of code! I'm not sure if you're familiar with Spyder IDE, but the only reason that stopped me from switching to vscode was its nice embedded IPython console, and here we are, I found your extension, and I find myself using vscode more and more. Thanks a lot! 

Yes, I used Spyder for quite sometime and before that Matlab.  Spyder was clunky and works great but lacks the refactoring capabilities of VSCode.  This motivated me to develop this extension.  I'm very glad it works for you and thank you for your feedbacks and reviews 😄.  

> Now back to my original question: is it possible to add a dedicated panel for plots (similar to Spyder IDE)?  

Answer is yes but not easy.  It would requires extensive work in understanding and interfacing the IPython API with the VSCode Panel API.  There is also low likelihood that the rendering is worth forcing to fit within a VSCode Panel.  I personally like the interactive part of Matplotlib than the embedded on the terminal or a panel like Spyder did.

**Comment by hoangKnLai** [comment]
At this time, I rather leave it to IPython community and MS figure it out if they want to incorporate IPython with this feature.
