### ISSUE TITLE
Publish to Open-VSX

### ISSUE THREAD

**Issue by silopolis** [hoangKnLai/vscode-ipython#40]
For us Codium users, please :pray: 

Thanks for sharing your work, take care
J

**Comment by hoangKnLai** [comment]
Will look into it 👌

**Comment by hoangKnLai** [comment]
Here you go:  https://open-vsx.org/extension/HoangKimLai/ipython

**Comment by silopolis** [comment]
You just got your face pinned on the FOSS support celerity Wall of Fame!

Have a beautiful evening, and many thanks :pray: 
J
