### ISSUE TITLE
ipython stuck when using ctrl_space

### ISSUE THREAD

**Issue by Johan1974** [hoangKnLai/vscode-ipython#46]
Hello,

Just using ipython with visual code and i like the syntax highlighting.  Out of habit i used ctrl_space for code completion but then the shell got stuck and i can not type further and have to remove the terminal and start again. Not sure if it is relevant to use this combination with ipython but it should not get stuck on this combination. 

For your information i am using the following versions:

Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
IPython 8.19.0 -- An enhanced Interactive Python. Type '?' for help.

Johan

**Comment by hoangKnLai** [comment]
Hi, I've not been able to reproduce the problem but will still keep an eye out for this.  Some note:  
- This extension only handle text sending between VSCode and IPython terminal  
- Shortcuts are managed by VSCode and by IPython
