### ISSUE TITLE
Re-use already open IPython console for running different files

### ISSUE THREAD

**Issue by ma-sadeghi** [hoangKnLai/vscode-ipython#5]
Currently, it seems that I need to open up a separate IPython console window for each file. It would be great if we could reuse the same IPython console for running different files.

**Comment by hoangKnLai** [comment]
Hmm.  This should be the case already as the run file search for available `IPython` tagged terminal name to run the file on.  The latest used (appear to be the case with VSCode open terminal list ordering) should do so well. 

Can you list the steps to recreate the problem?

**Comment by ma-sadeghi** [comment]
My bad, I just checked and indeed it seems to be the case. Not sure what was happening before...
