### ISSUE TITLE
Suggestion: Method to kill/restart the ipython kernel

### ISSUE THREAD

**Issue by jdegenstein** [hoangKnLai/vscode-ipython#56]
The jupyter interactive console in VSCode has a built-in button to restart the kernel. I think it would be valuable to have the same feature in this extension. I would suggest a hotkey instead of a button though.

Thanks for the great work on this extension, it is much improved with the move to `%run -i` from clipboard.

**Comment by hoangKnLai** [comment]
Hi.  Thanks for the suggestion :).  

Of course, restarting the kernel can be the same as closing and creating a new terminal.  However, to reset the kernel, IPython provides the `%reset -f` command such that the terminal doesn't need to be re-created.  And to kill the kernel: with the terminal panel selected `Ctrl + C` interrupts the current run.   

Try the `%reset -f` and let me know if it works for you.  Thanks!
