### ISSUE TITLE
support linking current terminal to python file

### ISSUE THREAD

**Issue by albert-ying** [hoangKnLai/vscode-ipython#57]
Hi there,

I sometimes need to run Python files on Tmux to avoid disruption when disconnecting from the server.

I'm wondering if it possible to create a command that link the current terminal session and python file? 

Thank you!

**Comment by hoangKnLai** [comment]
If VSCode session is detached, maybe this is your case, then the IPython terminal should still be there.  Have you try the `Create Dedicated Terminal (ctrl+shift+i  shift+c)`  command to create a dedicated terminal for a `.py` file?  One way to know it works is that the terminal name would change to the `.py` file name.
