### ISSUE TITLE
vscode remote terminal cannot use

### ISSUE THREAD

**Issue by QingShuiHU** [hoangKnLai/vscode-ipython#59]
ipython cannot automatically activate the conda environment on the vscode remote terminal, and ipython reports an error：
![image](https://github.com/user-attachments/assets/71e83a6b-67b1-4f7a-b301-08cc1f3d872e)
The remote terminal does not automatically activate the conda environment

**Comment by hoangKnLai** [comment]
Hi, it looks like you're using Python 3.8.13 ('sensity':conda) environment.  Note that the `IPython` extension doesn't activate the environment, it's the `MS Python` extension that does that.  Maybe that extension and/or vscode behaviors had change in newer version.  

What is the vscode version you're using?

**Comment by QingShuiHU** [comment]
Thank you for your reply.
I am using vscode version 1.91.1.
![image](https://github.com/user-attachments/assets/5cf9e35d-c9bf-4d01-88ef-dfca9dfea33f)
Note that I used vscode for remote development.It is true that the selected conda environment is not automatically activated in the remote terminal(The operating system of the server is Ubuntu).
![image](https://github.com/user-attachments/assets/0a06879e-2867-4e48-b37e-9965e6cda924)
Locally and not remotely, vscode can automatically activate the environment (by using Command Prompt)
How can I solve this problem, thank you

**Comment by hoangKnLai** [comment]
> Locally and not remotely, vscode can automatically activate the environment (by using Command Prompt)
How can I solve this problem, thank you

Are you using WSL to connect with the remote terminal?  Also, is the environment 'sensitive:conda' the remote environment?  

Typically, if the proper environment is selected, VSCode should be able to activate the terminal correctly.  So when you startup your remote terminal, check if the environment the remote terminal have access to vs. the environment current selected at the bottom right are the same.

**Comment by hoangKnLai** [comment]
It appears that the issue is resolved.
