### ISSUE TITLE
Support debug mode?

### ISSUE THREAD

**Issue by ma-sadeghi** [hoangKnLai/vscode-ipython#6]
Is it possible to support debug mode in IPython console?

**Comment by hoangKnLai** [comment]
Have you try the [magic debug](https://maxar.zoom.us/rec/share/HWFzSc0k0ElkYEcfIsj6Xnh48G6jcrXHDJl_bUgBqGeQF1tsW9-v35AH5gEU69gU.g-vhEt7_DW0iV6dg) command?

I've personally not a fan of the IPython debugger so I've only use interactive debugging instead.

**Comment by ma-sadeghi** [comment]
They hyperlink points to a Zoom meeting :happy a typo maybe? By interactive debugger, you mean vscode's native debugger?

**Comment by hoangKnLai** [comment]
> They hyperlink points to a Zoom meeting :happy a typo maybe? 

Whoops.  Fixed the link.  

> By interactive debugger, you mean vscode's native debugger?  

VSCode natively does not do debugging with any language from what I can tell.  It is up to the language extension to set that up.  Unfortunately, to tap into the IPython debugger directly would take more expertise with REPL and IPython API than what I currently have.  For direct debugging feature, maybe one day or if a contributor from IPython wants to take on this challenge.

**Comment by hoangKnLai** [comment]
Recommend to use Python base debugger with VSCode.  Microsoft team did a good job on this.  I don't think the IPython debugger can catch up and has too much overlap usage.
