### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by cokelid** [hoangKnLai/vscode-ipython#60]
Is this extension available on the vscode marketplace (I can't find it!)?
Otherwise do I need to manually create a package from this repo?
Perhaps add an "Installation" section to the documentation to address this?

**Comment by cokelid** [comment]
Apologies, I found it: https://marketplace.visualstudio.com/items?itemName=HoangKimLai.ipython
Still could be useful to add to README?

**Comment by cokelid** [comment]
I have created a PR with a small change to the README:
https://github.com/hoangKnLai/vscode-ipython/pull/61

**Comment by hoangKnLai** [comment]
> I have created a PR with a small change to the README: #61

Thanks! Will merge when I get a chance.
